import type { Snapshot } from '../../contracts/index.ts';
import type { LessonIntro } from './lesson-media.ts';
import './lesson.css';

type Props = { snapshot: Snapshot; intro?: LessonIntro; ready: boolean; readOnly?: boolean; now: number; send: (type: string, payload?: Record<string, unknown>) => void };
const steps = [
  { id: 'intro', title: 'Learn the essentials', short: 'Learn' },
  { id: 'demonstration', title: 'Watch the demonstration', short: 'Watch' },
  { id: 'placement', title: 'Find your hand position', short: 'Position' },
  { id: 'practice', title: 'Practice with your coach', short: 'Practice' },
] as const;
const evidenceLabels = { learner_confirmed: 'Confirmed by you', video_ended: 'Video finished', visual_observation: 'Camera observation', simulated_observation: 'Recording observation' };

export function CprLesson({ snapshot, intro, ready, readOnly, now, send }: Props) {
  const lesson = snapshot.lesson;
  if (!lesson) return null;
  const observation = lesson.lastObservation, demo = snapshot.demonstration;
  const done = lesson.phase === 'complete', paused = lesson.status === 'paused';
  const current = steps.findIndex(step => step.id === lesson.phase);
  const canAct = ready && !readOnly && snapshot.status === 'active';
  const act = (action: string) => send('lesson_action', { action, expectedRevision: lesson.revision });
  const age = observation ? Math.max(0, Math.floor((now - observation.at) / 1000)) : null;
  const stale = !!observation && now - observation.at > 5000;
  const availableClips = Array.isArray(snapshot.device?.demoAssets) ? snapshot.device.demoAssets as { lessonKey?: string }[] : [];
  const canPlay = (key: string) => canAct && !paused && !demo && availableClips.some(clip => clip.lessonKey === key);
  const placement = !observation ? 'Waiting for a clear view' : stale ? 'Waiting for a fresh observation' : observation.placement === 'too_low' ? 'Adjust your hand position' : observation.placement === 'correct' ? 'Hand position observed' : 'Hand position is unclear';
  return <section className="lesson-panel" aria-label="CPR practice lesson">
    <div className="lesson-topline"><span className="eyebrow">ADULT CPR · MANIKIN PRACTICE</span><span className={`lesson-live ${paused ? 'paused' : ''}`}><span className="dot" />{done ? 'Review' : paused ? 'Paused' : demo ? 'Demonstration' : snapshot.status === 'active' ? 'Coach connected' : snapshot.status}</span></div>
    <div className="lesson-title"><div><h2>{done ? 'Practice session complete.' : paused ? 'Take your time.' : steps[current]?.title ?? 'Your CPR practice'}</h2><p>{done ? 'Review what happened and what the camera could observe.' : 'Learn the movement. Try it on your manikin. Ask for help at any point.'}</p></div>{!readOnly && !done && <button className="secondary compact" disabled={!canAct || !!demo} onClick={() => act(paused ? 'resume' : 'pause')}>{paused ? 'Resume lesson' : 'Pause lesson'}</button>}</div>
    <ol className="lesson-steps" aria-label="Lesson progress">{steps.map((step, index) => {
      const completed = lesson.completed.find(item => item.step === step.id);
      return <li key={step.id} className={completed ? 'completed' : index === current ? 'current' : ''} aria-current={index === current ? 'step' : undefined}><span className="lesson-step-number">{completed ? '✓' : String(index + 1).padStart(2, '0')}</span><div><strong>{step.short}</strong><small>{completed ? completed.evidence === 'learner_confirmed' && step.id === 'placement' ? 'Continued without visual check' : completed.evidence === 'learner_confirmed' && step.id === 'demonstration' ? 'Skipped by you' : evidenceLabels[completed.evidence] : index === current ? 'In progress' : 'Up next'}</small></div></li>;
    })}</ol>
    {paused ? <div className="lesson-content"><h3>Your place is saved.</h3><p>Resume when your manikin and camera are ready.</p></div> : lesson.phase === 'intro' ? <div className="lesson-content lesson-intro">
      <div><span className="tiny">BEFORE YOU BEGIN</span><h3>Prepare your practice space.</h3><p>{intro?.scope ?? 'Use an adult manikin for this compression-only practice. Preparing the training reference…'}</p><p className="lesson-source">The points here come from the supplied CPR training dataset. Source links accompany each fact.</p></div>
      <div className="lesson-principles">{intro?.facts.map((fact, index) => <div key={fact.id}><span>{String(index + 1).padStart(2, '0')}</span><p>{fact.text}<a className="lesson-fact-source" href={fact.source.url} target="_blank" rel="noreferrer">{fact.source.title} ↗</a></p></div>) ?? <p>Loading the lesson reference…</p>}</div>
      {!readOnly && <div className="lesson-next"><span>Next: a short visual demonstration.</span><button className="primary" disabled={!canAct || !intro?.facts.length} onClick={() => act('continue')}>I’m ready to watch <span>→</span></button></div>}
    </div> : lesson.phase === 'demonstration' ? <div className="lesson-content lesson-watch"><div className="lesson-play-icon">▷</div><h3>{demo ? 'Watch the demonstration on the display.' : 'See the movement before you try it.'}</h3><p>{demo ? 'Coaching and camera observation pause during playback. Your lesson returns when the clip ends.' : 'The overview shows the movement. Later, ask “Can I see the hand placement again?” to replay just that moment.'}</p>{!readOnly && <button className="primary" disabled={!canPlay('overview')} onClick={() => send('play_training_video', { clipId: 'overview' })}>{demo ? 'Demonstration playing…' : 'Play overview'} <span>▷</span></button>}{!demo && !availableClips.some(clip => clip.lessonKey === 'overview') && <p className="lesson-media-note">Preparing the lesson video on your device. Media status appears below.</p>}{!readOnly && !demo && <div><button className="plain" disabled={!canAct} onClick={() => act('continue')}>Skip video and practice</button></div>}</div> : done ? <div className="lesson-content lesson-review"><div><span className="lesson-review-check">✓</span><h3>You finished this practice.</h3><p>Your checklist keeps learner confirmations, video playback, and camera observations separate. Completion is a record of this session, not a technique score or certification.</p></div><div><h4>What the camera can tell us</h4><p>Visible hand position and posture can support coaching. These frames do not measure compression depth, force, recoil, or a reliable compression rate.</p>{observation && <p>Last observation: {observation.reason}</p>}{!readOnly && <button className="secondary" disabled={!canAct} onClick={() => act('restart')}>Practice again <span>↗</span></button>}</div></div> : <div className="lesson-content lesson-practice">
      <div><span className="tiny">{lesson.phase === 'placement' ? 'SET UP YOUR POSITION' : 'LIVE PRACTICE'}</span><h3>{lesson.phase === 'placement' ? 'Show your hands and the manikin’s chest.' : 'Practice at your own pace.'}</h3><p>{lesson.phase === 'placement' ? 'Keep the chest landmarks and both hands in view. The coach will ask you to adjust if it can clearly see a placement issue.' : 'Ask for the hand-placement clip whenever you need it. Your practice resumes afterward.'}</p><div className="lesson-actions"><button className="secondary" disabled={!canPlay('hand-placement')} onClick={() => send('play_training_video', { clipId: 'hand-placement' })}>Show hand placement <span>▷</span></button>{lesson.phase === 'placement' && !readOnly && <button className="secondary" disabled={!canAct || !!demo} onClick={() => act('continue')}>Continue without visual check</button>}{lesson.phase === 'practice' && !readOnly && <button className="primary" disabled={!canAct || !!demo} onClick={() => act('finish_practice')}>I’ve finished practicing <span>✓</span></button>}</div>{lesson.phase === 'placement' && !readOnly && <p className="lesson-media-note">You can continue if the camera cannot check your position. This does not mark hand placement as verified.</p>}{demo && <p className="lesson-media-note">Reference clip playing. Observation resumes after playback.</p>}</div>
      <div className={`lesson-observation ${!stale && observation?.placement === 'too_low' ? 'adjust' : ''}`} aria-live="polite"><span className="tiny">CAMERA OBSERVATION</span><h4>{demo ? 'Paused for the demonstration' : placement}</h4><p>{demo ? 'The demonstration is not treated as learner performance.' : stale ? 'The last observation is no longer current. Keep the manikin and your hands in view.' : observation?.reason ?? 'Choose a camera recording below, press play, and enable camera uploads. On glasses, start the camera from the phone.'}</p>{!demo && !stale && lesson.feedback && <p className="lesson-feedback">{lesson.feedback}</p>}<div className="lesson-observation-meta"><span>{observation?.cameraSource === 'recorded_video' ? 'Recorded simulation' : observation?.cameraSource === 'mock' ? 'Synthetic simulation' : observation ? 'Camera frame' : 'No observation yet'}</span>{age !== null && <span>{age}s ago</span>}<span>{lesson.observerStatus === 'observing' ? 'Checking view…' : lesson.observerStatus === 'unavailable' ? 'Observer unavailable' : lesson.observerStatus === 'waiting_for_camera' ? 'Waiting for camera' : ''}</span></div>{lesson.observerError && <p className="lesson-observer-error" role="status">{lesson.observerError}</p>}</div>
    </div>}
    <div className="lesson-footnote"><span>Manikin only · AI practice guide</span><span>Camera feedback is qualitative. Use manikin sensors to measure compression quality.</span></div>
  </section>;
}
